CREATE SCHEMA bank;
CREATE TABLE IF NOT EXISTS accounts (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     customer VARCHAR(255) NOT NULL,
     balance DECIMAL(19, 4) NOT NULL DEFAULT 0,
     address VARCHAR(255),
     open_date VARCHAR(255)
);